# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IFV_MkO2Aw3Nr_UVZDQqoUn515f4JeZj
"""

import sys
n=int(input())
a=list(map(int,input().split()))
m=-1
mc=0
n=-sys.maxsize
for i in a:
    mc+=i
    if mc<0:
        n=max(mc,n)
        mc=0
    m=max(m,mc)
if m==0:
    print(n)
else:
    print(m)